---
- name: Launch the database container and Build an app with the command module on a remote docker host. Connect the app with database
  hosts: docker

  tasks:
    - name: Launch redis database
      docker_container:
        name: redis
        image: redis
        ports:
        - "6379:5000"

    - name: build the image
      command: docker build -t ansibleimage1 /root/web2/

    - name: run the site in a docker container
      docker_container:
        name: web
        image: "ansibleimage1"
        state: started
        ports:
        - "5000:5000"
        links:
        - redis:redis

    - name: Launch another instance of load-balancing container
      docker_container:
        state: started
        name: "web{{ item }}"
        image: "ansibleimage1"
        ports:
        - "5001:5000"
        links:
        - redis:redis
      with_sequence: count=1

    - name: Update the code and launch the app again
      copy:
        src: /root/app.py
        dest: /root/web2/app.py
        owner: root
        group: root
        mode: 777

    - name: build the image
      command: docker build -t ansibleimage1 /root/web2/

    - name: run the site in a docker container
      docker_container:
        name: web
        image: "ansibleimage1"
        state: started
        ports:
        - "5000:5000"
        links:
        - redis:redis
